const PDFDocument = require('pdfkit');
const fs = require('fs');

const cleanStr = (str) => {
  return (str || 'Not specified').replace(/[^\x00-\x7F]/g, (c) => {
    const m = { '→': '->', '•': '-', '…': '...' };
    return m[c] || ' ';
  });
};

const L = 50;
const getW = (doc) => doc.page.width - L * 2;

const drawHeader = (doc, mom) => {
  const W = doc.page.width;
  doc.rect(0, 0, W, 90).fill('#1a73e8');
  doc.fillColor('white').fontSize(24).font('Helvetica-Bold')
     .text('MINUTES OF MEETING', 0, 18, { align: 'center', width: W, lineBreak: false });
  doc.fillColor('rgba(255,255,255,0.85)').fontSize(12).font('Helvetica')
     .text(cleanStr(mom.meetingTitle), 0, 50, { align: 'center', width: W, lineBreak: false });
  doc.fillColor('rgba(255,255,255,0.6)').fontSize(8)
     .text('Generated by CRM — NoteLens Integration', 0, 72, { align: 'center', width: W, lineBreak: false });
};

const drawFooter = (doc) => {
  const W = doc.page.width;
  const H = doc.page.height;
  doc.rect(0, H - 30, W, 30).fill('#f5f5f5');
  doc.strokeColor('#e0e0e0').lineWidth(0.5).moveTo(0, H - 30).lineTo(W, H - 30).stroke();
  doc.fillColor('#aaa').fontSize(8).font('Helvetica')
     .text(
       `CRM MOM  |  Generated on ${new Date().toLocaleString('en-IN')}  |  Confidential`,
       0, H - 18, { align: 'center', width: W, lineBreak: false }
     );
};

const sectionTitle = (doc, title) => {
  const w = getW(doc);
  doc.moveDown(0.8);
  const y = doc.y;
  doc.rect(L, y, w, 26).fill('#1a73e8');
  doc.fillColor('white').fontSize(10).font('Helvetica-Bold')
     .text(title.toUpperCase(), L, y + 8, { width: w, align: 'center', lineBreak: false, characterSpacing: 1.5 });
  doc.y = y + 32;
};

const infoRow = (doc, label, value) => {
  const w = getW(doc);
  const y = doc.y;
  const labelW = 120;
  doc.rect(L, y, labelW, 22).fill('#e8f0fe');
  doc.fillColor('#1557b0').fontSize(9).font('Helvetica-Bold')
     .text(label, L + 6, y + 6, { width: labelW - 8, lineBreak: false });
  doc.rect(L + labelW, y, w - labelW, 22).fill('#f8f9fa');
  doc.strokeColor('#e0e0e0').lineWidth(0.5).rect(L, y, w, 22).stroke();
  doc.fillColor('#222').fontSize(9).font('Helvetica')
     .text(cleanStr(value), L + labelW + 6, y + 6, { width: w - labelW - 10, lineBreak: false });
  doc.y = y + 26;
};

const generateMOMPDF = (mom, outputPath) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4', margin: 0, autoFirstPage: false,
      info: { Title: 'Minutes of Meeting', Author: 'CRM' }
    });

    const ws = fs.createWriteStream(outputPath);
    ws.on('error', reject);
    doc.on('error', reject);
    doc.pipe(ws);
    doc.addPage();

    drawHeader(doc, mom);
    drawFooter(doc);
    doc.y = 106;
    const w = getW(doc);

    sectionTitle(doc, 'Meeting Details');
    infoRow(doc, 'Date', mom.meetingDate);
    infoRow(doc, 'Time', mom.meetingTime);
    infoRow(doc, 'Venue', mom.venue);
    infoRow(doc, 'Chairperson', mom.chairperson);
    infoRow(doc, 'Next Meeting', mom.nextMeetingDate);

    if (mom.attendees?.length > 0) {
      sectionTitle(doc, 'Attendees');
      const perRow = 3;
      const cellW = Math.floor(w / perRow);
      const rows = Math.ceil(mom.attendees.length / perRow);
      for (let r = 0; r < rows; r++) {
        const rowY = doc.y;
        for (let c = 0; c < perRow; c++) {
          const idx = r * perRow + c;
          if (idx >= mom.attendees.length) break;
          const cellX = L + c * cellW;
          doc.rect(cellX, rowY, cellW, 24).fill(idx % 2 === 0 ? '#f8f9fa' : '#fff');
          doc.rect(cellX, rowY, cellW, 24).stroke('#e8e8e8');
          doc.circle(cellX + 10, rowY + 12, 3).fill('#1a73e8');
          doc.fillColor('#222').fontSize(9.5).font('Helvetica')
             .text(cleanStr(mom.attendees[idx]), cellX + 18, rowY + 7, { width: cellW - 22, lineBreak: false });
        }
        doc.y = rowY + 28;
      }
    }

    if (mom.agenda?.length > 0) {
      sectionTitle(doc, 'Agenda');
      mom.agenda.forEach((item, i) => {
        const y = doc.y;
        doc.rect(L, y, 22, 20).fill('#1a73e8');
        doc.fillColor('white').fontSize(9).font('Helvetica-Bold')
           .text(`${i + 1}`, L, y + 5, { width: 22, align: 'center', lineBreak: false });
        doc.rect(L + 22, y, w - 22, 20).fill(i % 2 === 0 ? '#f8f9fa' : '#fff');
        doc.rect(L, y, w, 20).stroke('#e8e8e8');
        doc.fillColor('#222').fontSize(10).font('Helvetica')
           .text(cleanStr(item), L + 28, y + 4, { width: w - 32, lineBreak: false });
        doc.y = y + 24;
      });
    }

    if (mom.discussionPoints?.length > 0) {
      sectionTitle(doc, 'Discussion Points');
      mom.discussionPoints.forEach((dp) => {
        const topicY = doc.y;
        doc.rect(L, topicY, w, 22).fill('#e8f0fe');
        doc.rect(L, topicY, 4, 22).fill('#1a73e8');
        doc.fillColor('#1557b0').fontSize(10.5).font('Helvetica-Bold')
           .text(cleanStr(dp.topic), L + 10, topicY + 5, { width: w - 14, lineBreak: false });
        doc.y = topicY + 28;
        doc.fillColor('#333').fontSize(10).font('Helvetica')
           .text(cleanStr(dp.details), L + 8, doc.y, { width: w - 16, lineGap: 3 });
        doc.moveDown(0.5);
      });
    }

    if (mom.decisions?.length > 0) {
      sectionTitle(doc, 'Decisions Made');
      mom.decisions.forEach((d) => {
        const y = doc.y;
        doc.circle(L + 6, y + 5, 2.5).fill('#22c55e');
        doc.fillColor('#222').fontSize(10).font('Helvetica')
           .text(cleanStr(d), L + 16, y, { width: w - 20, lineGap: 3 });
        doc.moveDown(0.2);
      });
    }

    if (mom.actionItems?.length > 0) {
      sectionTitle(doc, 'Action Items');
      const col1W = Math.floor(w * 0.55);
      const col2W = Math.floor(w * 0.23);
      const col3W = w - col1W - col2W;
      const col1 = L, col2 = L + col1W, col3 = L + col1W + col2W;
      const rowH = 26;

      const hY = doc.y;
      doc.rect(col1, hY, col1W, rowH).fill('#1557b0');
      doc.rect(col2, hY, col2W, rowH).fill('#1557b0');
      doc.rect(col3, hY, col3W, rowH).fill('#1557b0');
      doc.fillColor('white').fontSize(9).font('Helvetica-Bold')
         .text('ACTION ITEM', col1 + 6, hY + 8, { width: col1W - 8, align: 'center', lineBreak: false })
         .text('OWNER', col2, hY + 8, { width: col2W, align: 'center', lineBreak: false })
         .text('DEADLINE', col3, hY + 8, { width: col3W, align: 'center', lineBreak: false });
      doc.y = hY + rowH;

      mom.actionItems.forEach((item, i) => {
        const rY = doc.y;
        const bg = i % 2 === 0 ? '#f8f9fa' : '#fff';
        doc.rect(col1, rY, col1W, rowH).fill(bg);
        doc.rect(col2, rY, col2W, rowH).fill(bg);
        doc.rect(col3, rY, col3W, rowH).fill(bg);
        doc.rect(col1, rY, w, rowH).stroke('#e0e0e0');
        doc.fillColor('#222').fontSize(9).font('Helvetica')
           .text(cleanStr(item.action), col1 + 6, rY + 7, { width: col1W - 10, lineBreak: false })
           .text(cleanStr(item.owner), col2 + 4, rY + 7, { width: col2W - 6, align: 'center', lineBreak: false })
           .text(cleanStr(item.deadline), col3 + 4, rY + 7, { width: col3W - 6, align: 'center', lineBreak: false });
        doc.y = rY + rowH;
      });
    }

    if (mom.additionalNotes && mom.additionalNotes !== 'Not specified') {
      sectionTitle(doc, 'Additional Notes');
      doc.fillColor('#444').fontSize(10).font('Helvetica')
         .text(cleanStr(mom.additionalNotes), L, doc.y, { width: w, lineGap: 5, align: 'justify' });
    }

    doc.moveDown(1.5);
    const sigY = doc.y;
    const sigW = 140;
    doc.strokeColor('#999').lineWidth(0.5)
       .moveTo(L, sigY).lineTo(L + sigW, sigY).stroke();
    doc.fillColor('#555').fontSize(8)
       .text('Prepared by', L, sigY + 5, { width: sigW, align: 'center', lineBreak: false });
    const approveX = L + w - sigW;
    doc.strokeColor('#999').moveTo(approveX, sigY).lineTo(approveX + sigW, sigY).stroke();
    doc.fillColor('#555').fontSize(8)
       .text('Approved by', approveX, sigY + 5, { width: sigW, align: 'center', lineBreak: false });

    doc.end();
    ws.on('finish', resolve);
  });
};

module.exports = { generateMOMPDF };